Update GA artifact v1 & v2 to v4
Test 2

diff --git a/.github/workflows/dev-cpp.yml b/.github/workflows/dev-cpp.yml
--- a/.github/workflows/dev-cpp.yml
+++ b/.github/workflows/dev-cpp.yml
@@ -1,11 +1,13 @@
-name: Continuous Integration on develop branch
+name: Continuous Integration on master branch
 on:
   push:
     branches:
+    - master
     - develop
     - aux-dev
   pull_request:
     branches:
+    - master
     - develop
 env:
   SOURCE_ARTIFACT: ${{ github.workspace }}/source
@@ -20,7 +22,7 @@ jobs:
       uses: actions/checkout@v2
     - name: Install Required Packages
       run: |
-        sudo apt-get install build-essential libtool autotools-dev automake autoconf-archive pkg-config libssl-dev libevent-dev bsdmainutils python3
+        sudo apt-get install build-essential libtool autotools-dev autoconf-archive automake pkg-config libssl-dev libevent-dev bsdmainutils python3
         sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
         sudo apt-get install libboost-all-dev
         sudo apt-get install libdb5.3-dev libdb5.3++-dev
@@ -32,7 +34,7 @@ jobs:
     - name: Create Distribution Tarball
       run: |
         ./autogen.sh
-        ./configure --with-incompatible-bdb --with-miniupnpc
+        ./configure --with-incompatible-bdb --with-miniupnpc CXXFLAGS="-std=c++11"
         make dist
     - name: Download Dependencies
       run: make -C depends download
@@ -63,23 +65,20 @@ jobs:
       run: |
         tar -xzf depends.tar.gz
         tar -xzf australiacash-*.tar.gz --strip-components=1
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Install Required Packages
       run: |
         sudo apt-get update
         sudo apt-get install -y python3-zmq
     - name: Build Dependencies
       run: make -C depends -j$(nproc)
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Build AustraliaCash
       run: |
-        ./configure --prefix=$(realpath depends/x86_64-pc-linux-gnu)
+        ./configure --prefix=$(realpath depends/x86_64-pc-linux-gnu) --disable-tests
         make -j$(nproc)
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Prepare Files for Artifact
       run: |
         mkdir -p $ARTIFACT_DIR
-        mv $SOURCE_ARTIFACT/src/{australiacash-cli,australiacash-tx,australiacashd,qt/australiacash-qt} $ARTIFACT_DIR
+        mv ./src/{australiacash-cli,australiacash-tx,australiacashd,qt/australiacash-qt} $ARTIFACT_DIR
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
@@ -100,7 +99,6 @@ jobs:
       run: |
         tar -xzf depends.tar.gz
         tar -xzf australiacash-*.tar.gz --strip-components=1
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Install Required Packages
       run: |
         sudo apt-get update
@@ -111,16 +109,14 @@ jobs:
         sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
     - name: Build Dependencies
       run: make -C depends -j$(nproc) HOST=x86_64-w64-mingw32
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
-    - name: Build AustraliaCash
+    - name: Build australiacash
       run: |
         ./configure --prefix=$(realpath depends/x86_64-w64-mingw32)
         make -j$(nproc)
-      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Prepare Files for Artifact
       run: |
         mkdir -p $ARTIFACT_DIR
-        mv $SOURCE_ARTIFACT/src/{australiacash-cli.exe,australiacash-tx.exe,australiacashd.exe,qt/australiacash-qt.exe} $ARTIFACT_DIR
+        mv ./src/{australiacash-cli.exe,australiacash-tx.exe,australiacashd.exe,qt/australiacash-qt.exe} $ARTIFACT_DIR
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
@@ -128,69 +124,69 @@ jobs:
         path: ${{ env.ARTIFACT_DIR }}
 
   # MacOS build script adapted from https://github.com/dogecoin/dogecoin/blob/master/.github/workflows/ci.yml
-  build-macos:
-    name: Build for MacOS
-    needs: create-source-distribution
-    runs-on: ubuntu-20.04
-    env:
-      name: x86_64-macos
-      host: x86_64-apple-darwin11
-      os: ubuntu-20.04
-      packages: cmake imagemagick libcap-dev librsvg2-bin libz-dev libtiff-tools libtinfo5 python3-setuptools xorriso libtinfo5
-      config-opts: "--enable-gui=qt5 --enable-reduce-exports"
-      goal: deploy
-      sdk: 10.11
-      sdk-url: "https://bitcoincore.org/depends-sources/sdks"
-    steps:
-      - name: Install packages
-        run: |
-          sudo apt-get update
-          sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3 rsync git procps bison
-          sudo apt-get install ${{ env.packages }}
-      - name: Checkout
-        uses: actions/checkout@v2
-      - name: SDK cache
-        if: ${{ env.sdk }}
-        uses: actions/cache@v2
-        env:
-          cache-name: sdk
-        with:
-          path: ./depends/sdk-sources
-          key: ${{ env.name }}-${{ env.cache-name }}
-      - name: Install SDK
-        if: ${{ env.sdk }}
-        run: |
-          mkdir -p ./depends/sdk-sources
-          mkdir -p ./depends/SDKs
-          curl --location --fail ${{ env.sdk-url }}/MacOSX${{ env.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
-          tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
-      - name: Dependency cache
-        uses: actions/cache@v2
-        env:
-          cache-name: depends
-        with:
-          path: ./depends/built
-          key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
-      - name: Build depends
-        run: |
-          make -C depends HOST=${{ env.host }}
-      - name: CCache
-        uses: actions/cache@v2
-        env:
-          cache-name: ccache
-        with:
-          path: ~/.ccache
-          key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
-      - name: Build AustraliaCash
-        run: |
-          depends/${{ env.host }}/native/bin/ccache --max-size=100M
-          ./autogen.sh
-          ./configure --prefix=`pwd`/depends/${{ env.host }} ${{ env.config-opts }} || ( cat config.log && false)
-          make ${{ env.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ env.goal }} V=1 ; false )
-          mv AustraliaCash-Core.dmg AustraliaCash.dmg
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-binaries
-          path: |
-            AustraliaCash.dmg
+  # build-macos:
+  #   name: Build for MacOS
+  #   needs: create-source-distribution
+  #   runs-on: ubuntu-20.04
+  #   env:
+  #     name: x86_64-macos
+  #     host: x86_64-apple-darwin11
+  #     os: ubuntu-20.04
+  #     packages: cmake imagemagick libcap-dev librsvg2-bin libz-dev libtiff-tools libtinfo5 python3-setuptools xorriso libtinfo5
+  #     config-opts: "--enable-gui=qt5 --enable-reduce-exports"
+  #     goal: deploy
+  #     sdk: 10.11
+  #     sdk-url: "https://bitcoincore.org/depends-sources/sdks"
+  #   steps:
+  #     - name: Install packages
+  #       run: |
+  #         sudo apt-get update
+  #         sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3 rsync git procps bison
+  #         sudo apt-get install ${{ env.packages }}
+  #     - name: Checkout
+  #       uses: actions/checkout@v2
+  #     - name: SDK cache
+  #       if: ${{ env.sdk }}
+  #       uses: actions/cache@v2
+  #       env:
+  #         cache-name: sdk
+  #       with:
+  #         path: ./depends/sdk-sources
+  #         key: ${{ env.name }}-${{ env.cache-name }}
+  #     - name: Install SDK
+  #       if: ${{ env.sdk }}
+  #       run: |
+  #         mkdir -p ./depends/sdk-sources
+  #         mkdir -p ./depends/SDKs
+  #         curl --location --fail ${{ env.sdk-url }}/MacOSX${{ env.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
+  #         tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
+  #     - name: Dependency cache
+  #       uses: actions/cache@v2
+  #       env:
+  #         cache-name: depends
+  #       with:
+  #         path: ./depends/built
+  #         key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
+  #     - name: Build depends
+  #       run: |
+  #         make -C depends HOST=${{ env.host }}
+  #     - name: CCache
+  #       uses: actions/cache@v2
+  #       env:
+  #         cache-name: ccache
+  #       with:
+  #         path: ~/.ccache
+  #         key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
+  #     - name: Build australiacash
+  #       run: |
+  #         depends/${{ env.host }}/native/bin/ccache --max-size=100M
+  #         ./autogen.sh
+  #         ./configure --prefix=`pwd`/depends/${{ env.host }} ${{ env.config-opts }} || ( cat config.log && false)
+  #         make ${{ env.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ env.goal }} V=1 ; false )
+  #         mv australiacash-Core.dmg australiacash.dmg
+  #     - name: Upload artifacts
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: macos-binaries
+  #         path: |
+  #           AustraliaCash.dmg
