Update GA artifact v1 & v2 to v4

diff --git a/.github/workflows/dev-cpp.yml b/.github/workflows/dev-cpp.yml
--- a/.github/workflows/dev-cpp.yml
+++ b/.github/workflows/dev-cpp.yml
@@ -1,34 +1,27 @@
-name: Continuous Integration For AustraliaCash
+name: Continuous Integration on develop branch
 on:
   push:
     branches:
-      - dev
-      - aux-dev
-      - master
-      - aux-master
+    - develop
   pull_request:
     branches:
-      - dev
-      - aux-dev
-      - master
-      - aux-master
+    - develop
 env:
-  SOURCE_ARTIFACT: source
+  SOURCE_ARTIFACT: ${{ github.workspace }}/source
 jobs:
   create-source-distribution:
     name: Create Source Distribution
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-20.04
     env:
-      ARTIFACT_DIR: source
+      ARTIFACT_DIR: ${{ github.workspace }}/artifacts/source
     steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Install Required Packages
       run: |
-        sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 autoconf-archive
+        sudo apt-get install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3
         sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev
         sudo apt-get install libboost-all-dev
-        sudo apt-get install software-properties-common
         sudo apt-get install libdb5.3-dev libdb5.3++-dev
         sudo apt-get update
         sudo apt-get install libminiupnpc-dev
@@ -38,7 +31,7 @@ jobs:
     - name: Create Distribution Tarball
       run: |
         ./autogen.sh
-        ./configure
+        ./configure --with-incompatible-bdb --with-miniupnpc
         make dist
     - name: Download Dependencies
       run: make -C depends download
@@ -49,42 +42,27 @@ jobs:
         mkdir -p $ARTIFACT_DIR
         mv depends.tar.gz australiacash-*.tar.gz $ARTIFACT_DIR
     - name: Upload Artifact
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
       with:
-        name: ${{ env.SOURCE_ARTIFACT }}
+        name: source
         path: ${{ env.ARTIFACT_DIR }}
-    - name: List Downloaded Files
-      run: |
-        ls -R source
-
-
-  build-linux-22:
-    name: Build for Linux 22
+  build-linux:
+    name: Build for Linux
     needs: create-source-distribution
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-20.04
     env:
-      ARTIFACT_DIR: linux-ubu22-binaries
+      ARTIFACT_DIR: ${{ github.workspace }}/artifacts/linux
       TEST_LOG_ARTIFACT_DIR: test-logs
     steps:
     - name: Getting Source
-      uses: actions/download-artifact@v3
+      uses: actions/download-artifact@v4
       with:
-        name: ${{ env.SOURCE_ARTIFACT }}
-        path: ${{ env.ARTIFACT_DIR }}
-    
-    # Debugging: List files in source directory
-    - name: Check source directory content
-      run: ls -R source
-    
+        name: source
     - name: Extract Archives
       run: |
-        # Ensure the file exists before attempting to move it
-        ls -la source
-        mv source/australiacash-2.02.01.tar.gz .
-        mv source/depends.tar.gz .
         tar -xzf depends.tar.gz
-        tar -xzf australiacash-2.02.01.tar.gz --strip-components=1
-
+        tar -xzf australiacash-*.tar.gz --strip-components=1
+      working-directory: ${{ env.SOURCE_ARTIFACT }}
     - name: Install Required Packages
       run: |
         sudo apt-get update
@@ -92,7 +70,7 @@ jobs:
     - name: Build Dependencies
       run: make -C depends -j$(nproc)
       working-directory: ${{ env.SOURCE_ARTIFACT }}
-    - name: Build Australiacash
+    - name: Build AustraliaCash
       run: |
         ./configure --prefix=$(realpath depends/x86_64-pc-linux-gnu)
         make -j$(nproc)
@@ -102,10 +80,116 @@ jobs:
         mkdir -p $ARTIFACT_DIR
         mv $SOURCE_ARTIFACT/src/{australiacash-cli,australiacash-tx,australiacashd,qt/australiacash-qt} $ARTIFACT_DIR
     - name: Upload Artifact
-      uses: actions/upload-artifact@v3
+      uses: actions/upload-artifact@v4
       with:
-        name: linux-ubu22-binaries
+        name: linux-binaries
+        path: ${{ env.ARTIFACT_DIR }}
+  build-windows:
+    name: Build for Windows
+    needs: create-source-distribution
+    runs-on: ubuntu-20.04
+    env:
+      ARTIFACT_DIR: ${{ github.workspace }}/artifacts/windows
+    steps:
+    - name: Getting Source
+      uses: actions/download-artifact@v4
+      with:
+        name: source
+    - name: Extract Archives
+      run: |
+        tar -xzf depends.tar.gz
+        tar -xzf australiacash-*.tar.gz --strip-components=1
+      working-directory: ${{ env.SOURCE_ARTIFACT }}
+    - name: Install Required Packages
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y g++-mingw-w64-x86-64 gcc-mingw-w64-x86-64
+    - name: Switch MinGW GCC and G++ to POSIX Threading
+      run: |
+        sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
+        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
+    - name: Build Dependencies
+      run: make -C depends -j$(nproc) HOST=x86_64-w64-mingw32
+      working-directory: ${{ env.SOURCE_ARTIFACT }}
+    - name: Build AustraliaCash
+      run: |
+        ./configure --prefix=$(realpath depends/x86_64-w64-mingw32)
+        make -j$(nproc)
+      working-directory: ${{ env.SOURCE_ARTIFACT }}
+    - name: Prepare Files for Artifact
+      run: |
+        mkdir -p $ARTIFACT_DIR
+        mv $SOURCE_ARTIFACT/src/{australiacash-cli.exe,australiacash-tx.exe,australiacashd.exe,qt/australiacash-qt.exe} $ARTIFACT_DIR
+    - name: Upload Artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: windows-binaries
         path: ${{ env.ARTIFACT_DIR }}
 
-
-# Additional jobs for Windows, macOS, and Linux 20 will follow the same pattern.
+  # MacOS build script adapted from https://github.com/dogecoin/dogecoin/blob/master/.github/workflows/ci.yml
+  build-macos:
+    name: Build for MacOS
+    needs: create-source-distribution
+    runs-on: ubuntu-20.04
+    env:
+      name: x86_64-macos
+      host: x86_64-apple-darwin11
+      os: ubuntu-20.04
+      packages: cmake imagemagick libcap-dev librsvg2-bin libz-dev libtiff-tools libtinfo5 python3-setuptools xorriso libtinfo5
+      config-opts: "--enable-gui=qt5 --enable-reduce-exports"
+      goal: deploy
+      sdk: 10.11
+      sdk-url: "https://bitcoincore.org/depends-sources/sdks"
+    steps:
+      - name: Install packages
+        run: |
+          sudo apt-get update
+          sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl ca-certificates ccache python3 rsync git procps bison
+          sudo apt-get install ${{ env.packages }}
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: SDK cache
+        if: ${{ env.sdk }}
+        uses: actions/cache@v2
+        env:
+          cache-name: sdk
+        with:
+          path: ./depends/sdk-sources
+          key: ${{ env.name }}-${{ env.cache-name }}
+      - name: Install SDK
+        if: ${{ env.sdk }}
+        run: |
+          mkdir -p ./depends/sdk-sources
+          mkdir -p ./depends/SDKs
+          curl --location --fail ${{ env.sdk-url }}/MacOSX${{ env.sdk }}.sdk.tar.gz -o depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
+          tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${{ env.sdk }}.sdk.tar.gz
+      - name: Dependency cache
+        uses: actions/cache@v2
+        env:
+          cache-name: depends
+        with:
+          path: ./depends/built
+          key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('depends/packages/*') }}
+      - name: Build depends
+        run: |
+          make -C depends HOST=${{ env.host }}
+      - name: CCache
+        uses: actions/cache@v2
+        env:
+          cache-name: ccache
+        with:
+          path: ~/.ccache
+          key: ${{ env.name }}-${{ env.cache-name }}-${{ hashFiles('**/configure.ac') }}
+      - name: Build AustraliaCash
+        run: |
+          depends/${{ env.host }}/native/bin/ccache --max-size=100M
+          ./autogen.sh
+          ./configure --prefix=`pwd`/depends/${{ env.host }} ${{ env.config-opts }} || ( cat config.log && false)
+          make ${{ env.goal }} || ( echo "Build failure. Verbose build follows." && make ${{ env.goal }} V=1 ; false )
+          mv AustraliaCash-Core.dmg AustraliaCash.dmg
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: macos-binaries
+          path: |
+            AustraliaCash.dmg
